language: c

matrix:
    include:
        -
            os: linux
            sudo: false
            dist: trusty
            compiler: gcc
    include:
        -
            os: linux
            sudo: false
            dist: trusty
            compiler: clang
    include:
        -
            os: osx
            env: HOMEBREW_NO_AUTO_UPDATE=1
            compiler: clang

addons:
    apt:
        packages:
        - ed
        - qemu-user

git:
    depth: 10
script:
    - make PREFIX=/tmp/acki

