matrix:
    include:
        -
            os: linux
            compiler: gcc
    include:
        -
            os: linux
            compiler: clang
    include:
        -
            os: osx
            env: HOMEBREW_NO_AUTO_UPDATE=1
            compiler: clang

addons:
    apt:
        packages:
        - ed
        - qemu-user

git:
    depth: 10
language: c
script:
    - make PREFIX=/tmp/acki

