matrix:
    include:
        - os: linux
        - os: osx

addons:
    apt:
        packages:
        - ed
        - qemu-system
        - openbios-ppc

git:
    depth: 10
sudo: required
language: c
script:
    - make PREFIX=/tmp/acki

