matrix:
    include:
        - os: linux
        - os: osx

addons:
    apt:
        packages:
        - ed
        - openbios-ppc
        - qemu-user

git:
    depth: 10
language: c
script:
    - make PREFIX=/tmp/acki

