name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: apt
      run: sudo apt update && sudo apt install bison flex ninja-build lua5.1 lua-posix
    - name: make
      run: make LUA=lua

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: brew
      run: brew install ninja lua@5.1 luarocks
    - name: luarocks
      run: |
        luarocks install --lua-version 5.1 luaposix 33.0.0-1
    - name: make
      run: |
        eval $(luarocks --lua-version 5.1 path)
        make LUA=/usr/local/bin/lua5.1

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW32
        install: >-
          make
          mingw-w64-i686-gcc
          mingw-w64-i686-lua51
          mingw-w64-i686-lua-luarocks
          ninja
          bison
          flex
          zip
    - name: luarocks
      run: |
        /mingw32/bin/luarocks --lua-version 5.1 install luaposix 33.0.0-1
    - uses: actions/checkout@v3
    - name: build
      run: |
        make LUA=/mingw32/bin/lua5.1

